<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MVTL1076LT" name="day_1.Session1" tests="2" failures="1" timestamp="27 Jan 2017 11:09:57 GMT" time="56.262" errors="0">
  <testcase name="AasserionsTest" time="27.827" classname="day_1.Session1">
    <failure type="java.lang.AssertionError" message="Iam done with Assertions expected [Demo Windows for practicing Selenium Automation1] but found [Demo Windows for practicing Selenium Automation]">
      <![CDATA[java.lang.AssertionError: Iam done with Assertions expected [Demo Windows for practicing Selenium Automation1] but found [Demo Windows for practicing Selenium Automation]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at day_1.Session1.AasserionsTest(Session1.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AasserionsTest -->
  <testcase name="test2" time="28.435" classname="day_1.Session1"/>
</testsuite> <!-- day_1.Session1 -->
